name: Build Singularity Container

on:
  push:
    branches:
      - main  # Triggers on a push to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/apptainer/apptainer:1.2.2

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Singularity
      - name: Install Singularity
        run: |
          sudo apt-get update
          sudo apt-get install -y singularity-container

      # Step 3: Build Singularity Image
      - name: Build Singularity Image
        run: |
          singularity build --debug pixy.sif miniconda.def

      # Step 4: Create GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0  # Change this for each version
          release_name: Singularity Container v1.0.0
          draft: false
          prerelease: false

      # Step 5: Upload Singularity Image to Release
      - name: Upload Singularity Image
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pixy.sif
          asset_name: pixy.sif
          asset_content_type: application/octet-stream
